### ISSUE TITLE
Function description highlight error

### ISSUE THREAD

**Issue by Bit0r** [bmalehorn/vscode-fish#10]
`--description` is highlighted as a string, not a parameter
![image](https://user-images.githubusercontent.com/43108543/86203330-547aa100-bb97-11ea-8b31-422c6433881f.png)

**Comment by bmalehorn** [comment]
Technically, the fish extension highlights does recognize `--description` as different than plains strings. The extension labels options as `string.other.option.fish`. But the default VSCode Dark+ theme does not have a special case for `string.other.option.fish` and highlights it as just a `string`.

https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

![image](https://user-images.githubusercontent.com/3344958/86290226-f0a9a580-bba1-11ea-88ed-e651e7ce0b90.png)

So it's not highlighted correctly because **the default VSCode theme does not have a color for command-line option**.

I could work around this by instead **inaccurately labeling the string as `string.regexp`**. This would get a distinct color, but might mislead users into thinking it was a regexp:

![image](https://user-images.githubusercontent.com/3344958/86290528-6b72c080-bba2-11ea-96ba-7a3b19c328dd.png)

A third option is to do no special highlighting:

![image](https://user-images.githubusercontent.com/3344958/86290736-cd332a80-bba2-11ea-91d6-9a4fefedbaaa.png)

@Bit0r What do you think would make the most sense?

**Comment by Bit0r** [comment]
Is there any difference between the second picture and the third picture, is the wrong picture uploaded?
But I think it can be highlighted as a `label` or `macro`?

**Comment by Bit0r** [comment]
Latest fish also supports logical operators such as `&&` `||` `!`, hope to add highlighting support :)
There are also two special symbols `&``|`, which can be highlighted as bit operators (although they are not bit operations, they can be done)

**Comment by bmalehorn** [comment]
> Is there any difference between the second picture and the third picture, is the wrong picture uploaded?
Ah yup, I uploaded the wrong picture. I've now uploaded the correct picture.

> Latest fish also supports logical operators such as `&&` `||` `!`, hope to add highlighting support :)
> There are also two special symbols `&` `|`, which can be highlighted as bit operators (although they are not bit operations, they can be done)

Ah, fish does correctly label `&&`, `||`, `!`, `&` and `|`! But the default Dark+ theme highlights them as plain white text. It does the same thing in JavaScript code - `&&` is highlighted as plain white text. However some themes do highlight it:

| Dark+ (default dark) | Monokai |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3344958/86395927-e812a700-bc55-11ea-995e-0463e5caed64.png) | ![image](https://user-images.githubusercontent.com/3344958/86395981-01b3ee80-bc56-11ea-9b21-3f9b0e00d9c1.png) |
 | ![image](https://user-images.githubusercontent.com/3344958/86395930-e8ab3d80-bc55-11ea-9573-861fd03f842c.png) | ![image](https://user-images.githubusercontent.com/3344958/86395983-024c8500-bc56-11ea-9ea6-6bd63cee241c.png) |


So it's not a problem of vscode-fish not labeling the text correctly, but rather that the Dark+ theme does not highlight every scope with a different color. I'd recommend trying out different themes to see if you can find one that highlights what you want.

> But I think it can be highlighted as a `label` or `macro`?

It looks like labels aren't highlighted any differently, but macros are:

![image](https://user-images.githubusercontent.com/3344958/86396682-42603780-bc57-11ea-9888-298c7ce3264f.png)

Still, I'm kind of leaning towards removing the syntax highlighting entirely on `--option` flags. They don't mean anything special in fish, `--option` is no different than `option`, it just has a conventional meeting. So the most accurate thing might be to not highlight it at all. Thoughts?

**Comment by Bit0r** [comment]
I think this is a good idea
