### ISSUE TITLE
Error reported for switch statements

### ISSUE THREAD

**Issue by rgwood** [bmalehorn/vscode-fish#2]
Using the `switch` example from [the official Fish tutorial](https://fishshell.com/docs/current/tutorial.html#tut_conditionals), `vscode-fish` reports an error on the very first line: "switch: Expected exactly one argument, got 0".

I'm using version 1.0.10 of the extension on macOS. Thanks for making the extension!

```fish
switch (uname)
case Linux
    echo Hi Tux!
case Darwin
    echo Hi Hexley!
case FreeBSD NetBSD DragonFly
    echo Hi Beastie!
case '*'
    echo Hi, stranger!
end
```

**Comment by johnaoss** [comment]
@rgwood Sadly this looks like its actually a bug in fish proper rather than the extension.

You get the same output if you put into a script, then execute it with the fish syntax checker by running:

```
fish -n script.fish
```

Although it looks like the issue was fixed in https://github.com/fish-shell/fish-shell/issues/5750, there hasn't been a stable release since. If you want, the beta release came out recently which you can try https://github.com/fish-shell/fish-shell/releases/tag/3.1b1

**Comment by rgwood** [comment]
Thank you for investigating this!
