### ISSUE TITLE
Something about this fish extension causes fish syntax to not work with multiple cursors

### ISSUE THREAD

**Issue by macintacos** [bmalehorn/vscode-fish#27]
I'm a heavy user of multiple cursors in VSCode, and for whatever reason this extension seems to stop it from working. When I add multiple cursors to a file and then hit any arrow direction, the cursors get dismissed. This behavior doesn't seem to happen when I switch to a new syntax for the exact same file (like for example, Python or JS or whatever).

Can this be looked into? Would love to continue using this extension. Please let me know if you need anything else on my end. Thanks!

**Comment by bmalehorn** [comment]
@macintacos thanks for the bug report.

1. Could you try disabling the extension, reloading, and trying to reproduce the issue? In general I want to confirm it never happens when the extension is disabled, and immediately happens in the same situation with the extension enabled.
2. Could you provide:
   - a sample file
   - a list of steps to reproduce the problem

I tried doing what you described but it worked fine for me:

https://user-images.githubusercontent.com/3344958/160935162-51446bb5-70eb-40db-ac5d-aba7ad0fda8e.mp4
